<?php

namespace Database\Seeders;

use App\Models\Tag;
use Illuminate\Database\Seeder;

class tagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arr = [
            ['nome'=>'Tags Versão Tiss','obs'=>'Informa a versão do TISS.','ordem'=>1],
            ['nome'=>'Tags Codigo do CBO','obs'=>'Código Cbo.','ordem'=>2],
            ['nome'=>'Tags Concelho do profissional','obs'=>'Código Cbo.','ordem'=>3],
            ['nome'=>'Tags Tabelas e taxas','obs'=>'Tabelas de valores.','ordem'=>4],
            ['nome'=>'Tags Motivos do encerramento','obs'=>'Motivos do encerramento da internação.','ordem'=>5],
            ['nome'=>'Tipos de guias','obs'=>'Tipos de guias','ordem'=>6],
            ['nome'=>'Código de despesa','obs'=>'Código de despesa','ordem'=>7],
            ['nome'=>'Unidade de medida','obs'=>'Unidade de medida','ordem'=>8],
            [
                "value"=>"3.02.00",
                "nome"=>"Tiss Versão 3.02.00",
                "pai"=>"1",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"3.02.01",
                "nome"=>"Tiss Versão 3.02.01",
                "pai"=>"1",
                "ordem"=>"2",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"3.02.02",
                "nome"=>"Tiss Versão 3.02.02",
                "pai"=>"1",
                "ordem"=>"3",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"3.03.00",
                "nome"=>"Tiss Versão 3.03.00",
                "pai"=>"1",
                "ordem"=>"4",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"3.03.01",
                "nome"=>"Tiss Versão 3.03.01",
                "pai"=>"1",
                "ordem"=>"5",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"3.03.02",
                "nome"=>"Tiss Versão 3.03.02",
                "pai"=>"1",
                "ordem"=>"6",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"3.03.03",
                "nome"=>"Tiss Versão 3.03.03",
                "pai"=>"1",
                "ordem"=>"7",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"3.04.00",
                "nome"=>"Tiss Versão 3.04.00",
                "pai"=>"1",
                "ordem"=>"8",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"3.04.01",
                "nome"=>"Tiss Versão 3.04.01",
                "pai"=>"1",
                "ordem"=>"9",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"3.05.00",
                "nome"=>"Tiss Versão 3.05.00",
                "pai"=>"1",
                "ordem"=>"10",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"18",
                "nome"=>"18 - TUSS - Taxas hospitalares, diárias e gases medicinais",
                "pai"=>"4",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"19",
                "nome"=>"19 - TUSS - Materiais",
                "pai"=>"4",
                "ordem"=>"2",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"20",
                "nome"=>"20 - TUSS - Medicamentos",
                "pai"=>"4",
                "ordem"=>"3",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"22",
                "nome"=>"22 - TUSS - Procedimentos e eventos em saúde (medicina, odonto e demais áreas de saúde)",
                "pai"=>"4",
                "ordem"=>"4",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"90",
                "nome"=>"90 - Tabela Própria Pacote Odontológico",
                "pai"=>"4",
                "ordem"=>"5",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"98",
                "nome"=>"98 - Tabela Própria de Pacotes",
                "pai"=>"4",
                "ordem"=>"6",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"00",
                "nome"=>"00 - Tabela Própria das Operadoras",
                "pai"=>"4",
                "ordem"=>"7",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"1",
                "nome"=>"CRAS",
                "pai"=>"3",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"2",
                "nome"=>"COREN",
                "pai"=>"3",
                "ordem"=>"2",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"3",
                "nome"=>"CRF",
                "pai"=>"3",
                "ordem"=>"3",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"4",
                "nome"=>"CRFA",
                "pai"=>"3",
                "ordem"=>"4",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"5",
                "nome"=>"CREFITO",
                "pai"=>"3",
                "ordem"=>"5",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"6",
                "nome"=>"CRM",
                "pai"=>"3",
                "ordem"=>"6",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"7",
                "nome"=>"CRN",
                "pai"=>"3",
                "ordem"=>"7",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"8",
                "nome"=>"CRO",
                "pai"=>"3",
                "ordem"=>"8",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"9",
                "nome"=>"CRP",
                "pai"=>"3",
                "ordem"=>"9",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"10",
                "nome"=>"OUTROS",
                "pai"=>"3",
                "ordem"=>"10",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"201115",
                "nome"=>"201115 - Geneticista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"203015",
                "nome"=>"203015 - Pesquisador em biologia de microorganismos e parasitas",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"213150",
                "nome"=>"213150 - Físico médico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"221105",
                "nome"=>"221105 - Biólogo",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225105",
                "nome"=>"225105 - Médico acupunturista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225110",
                "nome"=>"225110 - Médico alergista e imunologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225148",
                "nome"=>"225148 - Médico anatomopatologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225115",
                "nome"=>"225115 - Médico angiologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225120",
                "nome"=>"225120 - Médico cardiologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225210",
                "nome"=>"225210 - Médico cirurgião cardiovascular",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225215",
                "nome"=>"225215 - Médico cirurgião de cabeça e pescoço",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225220",
                "nome"=>"225220 - Médico cirurgião do aparelho digestivo",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225225",
                "nome"=>"225225 - Médico cirurgião geral",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225230",
                "nome"=>"225230 - Médico cirurgião pediátrico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225235",
                "nome"=>"225235 - Médico cirurgião plástico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225240",
                "nome"=>"225240 - Médico cirurgião torácico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225305",
                "nome"=>"225305 - Médico citopatologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225125",
                "nome"=>"225125 - Médico clínico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225130",
                "nome"=>"225130 - Médico de família e comunidade",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225135",
                "nome"=>"225135 - Médico dermatologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225140",
                "nome"=>"225140 - Médico do trabalho",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225310",
                "nome"=>"225310 - Médico em endoscopia",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225145",
                "nome"=>"225145 - Médico em medicina de tráfego",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225150",
                "nome"=>"225150 - Médico em medicina intensiva",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225315",
                "nome"=>"225315 - Médico em medicina nuclear",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225320",
                "nome"=>"225320 - Médico em radiologia e diagnóstico por imagem",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225155",
                "nome"=>"225155 - Médico endocrinologista e metabologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225160",
                "nome"=>"225160 - Médico fisiatra",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225245",
                "nome"=>"225245 - Médico foniatra",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225165",
                "nome"=>"225165 - Médico gastroenterologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225170",
                "nome"=>"225170 - Médico generalista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225175",
                "nome"=>"225175 - Médico geneticista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225180",
                "nome"=>"225180 - Médico geriatra",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225250",
                "nome"=>"225250 - Médico ginecologista e obstetra",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225185",
                "nome"=>"225185 - Médico Hematologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225190",
                "nome"=>"225190 - Médico Hemoterapeuta",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225195",
                "nome"=>"225195 - Médico Homeopata",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225103",
                "nome"=>"225103 - Médico infectologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225106",
                "nome"=>"225106 - Médico legista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225255",
                "nome"=>"225255 - Médico Mastologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225109",
                "nome"=>"225109 - Médico Nefrologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225260",
                "nome"=>"225260 - Médico neurocirurgião",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225350",
                "nome"=>"225350 - Médico neurofisiologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225112",
                "nome"=>"225112 - Médico neurologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225118",
                "nome"=>"225118 - Médico nutrologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225265",
                "nome"=>"225265 - Médico oftalmologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225121",
                "nome"=>"225121 - Médico oncologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225270",
                "nome"=>"225270 - Médico ortopedista e traumatologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225275",
                "nome"=>"225275 - Médico otorrinolaringologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225325",
                "nome"=>"225325 - Médico patologista clínico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225124",
                "nome"=>"225124 - Médico pediatra",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225127",
                "nome"=>"225127 - Médico pneumologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225280",
                "nome"=>"225280 - Médico proctologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225133",
                "nome"=>"225133 - Médico psiquiatra",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225330",
                "nome"=>"225330 - Médico radioterapeuta",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225136",
                "nome"=>"225136 - Médico reumatologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225139",
                "nome"=>"225139 - Médico sanitarista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225285",
                "nome"=>"225285 - Médico urologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223204",
                "nome"=>"223204 - Cirurgião dentista - auditor",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223208",
                "nome"=>"223208 - Cirurgião dentista - clínico geral",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223212",
                "nome"=>"223212 - Cirurgião dentista - endodontista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223216",
                "nome"=>"223216 - Cirurgião dentista - epidemiologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223220",
                "nome"=>"223220 - Cirurgião dentista - estomatologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223224",
                "nome"=>"223224 - Cirurgião dentista - implantodontista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223228",
                "nome"=>"223228 - Cirurgião dentista - odontogeriatra",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223232",
                "nome"=>"223232 - Cirurgião dentista - odontologista legal",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223236",
                "nome"=>"223236 - Cirurgião dentista - odontopediatra",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223240",
                "nome"=>"223240 - Cirurgião dentista - ortopedista e ortodontista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223244",
                "nome"=>"223244 - Cirurgião dentista - patologista bucal",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223248",
                "nome"=>"223248 - Cirurgião dentista - periodontista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223252",
                "nome"=>"223252 - Cirurgião dentista - protesiólogo bucomaxilofacial",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223256",
                "nome"=>"223256 - Cirurgião dentista - protesista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223260",
                "nome"=>"223260 - Cirurgião dentista - radiologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223264",
                "nome"=>"223264 - Cirurgião dentista - reabilitador oral",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223268",
                "nome"=>"223268 - Cirurgião dentista - traumatologista bucomaxilofacial",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223272",
                "nome"=>"223272 - Cirurgião dentista de saúde coletiva",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223505",
                "nome"=>"223505 - Enfermeiro",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223605",
                "nome"=>"223605 - Fisioterapeuta geral",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223910",
                "nome"=>"223910 - Ortoptista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223620",
                "nome"=>"223620 - Peripatologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223905",
                "nome"=>"223905 - Terapeuta ocupacional",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223710",
                "nome"=>"223710 - Nutricionista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223810",
                "nome"=>"223810 - Fonoaudiólogo",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"239425",
                "nome"=>"239425 - Psicopedagogo",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"251510",
                "nome"=>"251510 - Psicólogo clínico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"251545",
                "nome"=>"251545 - Neuropsicólogo",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"251550",
                "nome"=>"251550 - Psicanalista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"251605",
                "nome"=>"251605 - Assistente social",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"322205",
                "nome"=>"322205 - Técnico de enfermagem",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"322220",
                "nome"=>"322220 - Técnico de enfermagem psiquiátrica",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"322225",
                "nome"=>"322225 - Instrumentador cirúrgico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"322230",
                "nome"=>"322230 - Auxiliar de enfermagem",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"516210",
                "nome"=>"516210 - Cuidador de idosos",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225121",
                "nome"=>"225121 - Médico oncologista clínico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225325",
                "nome"=>"225325 - Médico patologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223276",
                "nome"=>"223276 - Cirurgião dentista - odontologia do trabalho",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223280",
                "nome"=>"223280 - Cirurgião dentista - dentística",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223284",
                "nome"=>"223284 - Cirurgião dentista - disfunção temporomandibular e dor orofacial",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223288",
                "nome"=>"223288 - Cirurgião dentista - odontologia para pacientes com necessidades especiais",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223293",
                "nome"=>"223293 - Cirurgião-dentista da estratégia de saúde da família",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225122",
                "nome"=>"225122 - Médico cancerologista pediátrico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225142",
                "nome"=>"225142 - Médico da estratégia de saúde da família",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225151",
                "nome"=>"225151 - Médico anestesiologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225203",
                "nome"=>"225203 - Médico em cirurgia vascular",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225290",
                "nome"=>"225290 - Médico cancerologista cirúrgico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225295",
                "nome"=>"225295 - Médico cirurgião da mão",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225335",
                "nome"=>"225335 - Médico patologista clínico / medicina laboratorial",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225340",
                "nome"=>"225340 - Médico hemoterapeuta",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225345",
                "nome"=>"225345 - Médico hiperbarista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223625",
                "nome"=>"223625 - Fisioterapeuta respiratória",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223630",
                "nome"=>"223630 - Fisioterapeuta neurofuncional",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223640",
                "nome"=>"223640 - Fisioterapeuta osteopata",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223645",
                "nome"=>"223645 - Fisioterapeuta quiropraxista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223650",
                "nome"=>"223650 - Fisioterapeuta acupunturista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223655",
                "nome"=>"223655 - Fisioterapeuta esportivo",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223660",
                "nome"=>"223660 - Fisioterapeuta do trabalho",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223435",
                "nome"=>"223435 - Farmacêutico industrial",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223430",
                "nome"=>"223430 - Farmacêutico em saúde pública",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223415",
                "nome"=>"223415 - Farmacêutico analista clínico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223405",
                "nome"=>"223405 - Farmacêutico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223420",
                "nome"=>"223420 - Farmacêutico de alimentos",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223440",
                "nome"=>"223440 - Farmacêutico toxicologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223445",
                "nome"=>"223445 - Farmacêutico hospitalar e clínico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223425",
                "nome"=>"223425 - Farmacêutico práticas integrativas e complementares",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223565",
                "nome"=>"223565 - Enfermeiro da estratégia de saúde da família",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223560",
                "nome"=>"223560 - Enfermeiro sanitarista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223555",
                "nome"=>"223555 - Enfermeiro puericultor e pediátrico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223550",
                "nome"=>"223550 - Enfermeiro psiquiátrico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223545",
                "nome"=>"223545 - Enfermeiro obstétrico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223540",
                "nome"=>"223540 - Enfermeiro neonatologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223535",
                "nome"=>"223535 - Enfermeiro nefrologista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223530",
                "nome"=>"223530 - Enfermeiro do trabalho",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223525",
                "nome"=>"223525 - Enfermeiro de terapia intensiva",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223520",
                "nome"=>"223520 - Enfermeiro de centro cirúrgico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223515",
                "nome"=>"223515 - Enfermeiro de bordo",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223510",
                "nome"=>"223510 - Enfermeiro auditor",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223570",
                "nome"=>"223570 - Perfusionista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223705",
                "nome"=>"223705 - Dietista",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223845",
                "nome"=>"223845 - Fonoaudiólogo em voz",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223830",
                "nome"=>"223830 - Fonoaudiólogo em linguagem",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223825",
                "nome"=>"223825 - Fonoaudiólogo em disfagia",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223835",
                "nome"=>"223835 - Fonoaudiólogo em motricidade orofacial",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223840",
                "nome"=>"223840 - Fonoaudiólogo em saúde coletiva",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223820",
                "nome"=>"223820 - Fonoaudiólogo em audiologia",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223815",
                "nome"=>"223815 - Fonoaudiólogo educacional",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"223915",
                "nome"=>"223915 - Musicoterapeuta",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"225154",
                "nome"=>"225154 - Médico antroposófico",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"226305",
                "nome"=>"226305 - Musicoterapeuta",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"999999",
                "nome"=>"999999 - CBO-S desconhecido ou não informado pelo solicitante",
                "pai"=>"2",
                "ordem"=>"1",
                "obs"=>"",
                "config"=>"",
            ],
            [
                "value"=>"11",
                "nome"=>"Alta Curado",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"12",
                "nome"=>"Alta Melhorado",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"13",
                "nome"=>"Alta da Puérpera e permanência do recém-nascido",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"14",
                "nome"=>"Alta a pedido",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"15",
                "nome"=>"Alta com previsão de retorno para acompanhamento do paciente",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"16",
                "nome"=>"Alta por Evasão",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"17",
                "nome"=>"Alta da Puérpera e recém-nascido",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"18",
                "nome"=>"Alta por Outros motivos",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"21",
                "nome"=>"Permanencia por características próprias da doença",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"22",
                "nome"=>"Permanencia por Intercorrência",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"23",
                "nome"=>"Permanencia por impossibilidade sócio-familiar",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"24",
                "nome"=>"permanencia por Processo de doação de órgãos, tecidos e células - doador vivo",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"25",
                "nome"=>"Permanencia por Processo de doação de órgãos, tecidos e células - doador morto",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"26",
                "nome"=>"Permanencia por mudança de procedimento",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"27",
                "nome"=>"Permanencia por re-operação",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"28",
                "nome"=>"Permanencia por outros motivos",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"31",
                "nome"=>"Transferido para outro estabelecimento",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"41",
                "nome"=>"Óbito com declaração de óbito fornecida pelo médico assistente",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"42",
                "nome"=>"Óbito com declaração de Óbito fornecida pelo Instituto Médico Legal - IML",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"43",
                "nome"=>"Óbito com declaração de Óbito fornecida pelo Serviço de Verificação de Óbito - SVO.",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            [
                "value"=>"51",
                "nome"=>"ENCERRAMENTO ADMINISTRATIVO",
                "config"=>"",
                "pai"=>"5",
                "ordem"=>"1",
                "obs"=>""
            ],
            //tipos de guias
            [
                "value"=>"spsadt",
                "nome"=>"Guia de SP/SADT",
                "config"=>"",
                "pai"=>"6",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"consulta",
                "nome"=>"Guia de Consulta",
                "config"=>"",
                "pai"=>"6",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"honorario",
                "nome"=>"Guia de Honorário Individual",
                "config"=>"",
                "pai"=>"6",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"internacao",
                "nome"=>"Guia de Resumo de Internação",
                "config"=>"",
                "pai"=>"6",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"glosa",
                "nome"=>"Guia de Recurso de Glosa",
                "config"=>"",
                "pai"=>"6",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"1",
                "nome"=>"Gases medicinais - (01)",
                "config"=>"",
                "pai"=>"7",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"2",
                "nome"=>"Medicamentos - (02)",
                "config"=>"",
                "pai"=>"7",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"3",
                "nome"=>"Materiais - (03)",
                "config"=>"",
                "pai"=>"7",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"5",
                "nome"=>"Diárias - (05)",
                "config"=>"",
                "pai"=>"7",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"7",
                "nome"=>"Taxas e aluguéis - (07)",
                "config"=>"",
                "pai"=>"7",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"8",
                "nome"=>"OPME - (08)",
                "config"=>"",
                "pai"=>"7",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"1",
                "nome"=>"AMP - (Ampola)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"2",
                "nome"=>"BUI - (Bilhões de Unidades Internacionais)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"3",
                "nome"=>"BG - (Bisnaga)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"4",
                "nome"=>"BOLS - (Bolsa)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"5",
                "nome"=>"CX - (Caixa)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"6",
                "nome"=>"CAP - (Cápsula)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"7",
                "nome"=>"CARP - (Carpule)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"8",
                "nome"=>"COM - (Comprimido)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"9",
                "nome"=>"DOSE - (Dose)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"10",
                "nome"=>"DRG - (Drágea)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"11",
                "nome"=>"ENV - (Envelope)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"12",
                "nome"=>"FLAC - (Flaconete)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"13",
                "nome"=>"FR - (Frasco)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"14",
                "nome"=>"FA - (Frasco Ampola)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"15",
                "nome"=>"GAL - (Galão)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"16",
                "nome"=>"GLOB - (Glóbulo)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"17",
                "nome"=>"GTS - (Gotas)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"18",
                "nome"=>"G - (Grama)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"19",
                "nome"=>"L - (Litro)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"20",
                "nome"=>"MCG - (Microgramas)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"21",
                "nome"=>"MUI - (Milhões de Unidades Internacionais)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"22",
                "nome"=>"MG - (Miligrama)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"23",
                "nome"=>"ML - (Milímetro)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"24",
                "nome"=>"OVL - (Óvulo)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"25",
                "nome"=>"PAS - (Pastilha)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"26",
                "nome"=>"LT - (Lata)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"27",
                "nome"=>"PER - (Pérola)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"28",
                "nome"=>"PIL - (Pílula)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"29",
                "nome"=>"PT - (Pote)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"30",
                "nome"=>"KG - (Quilograma)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"31",
                "nome"=>"SER - (Seringa)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"32",
                "nome"=>"SUP - (Supositório)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"33",
                "nome"=>"TABLE - (Tablete )",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"34",
                "nome"=>"TUB - (Tubete)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"35",
                "nome"=>"TB - (Tubo)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"36",
                "nome"=>"UN - (Unidade)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"37",
                "nome"=>"UI - (Unidade Internacional )",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"38",
                "nome"=>"CM - (Centímetro)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"39",
                "nome"=>"CONJ - (Conjunto)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"40",
                "nome"=>"KIT - (Kit)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"41",
                "nome"=>"MÇ - (Maço)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"42",
                "nome"=>"M - (Metro)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"43",
                "nome"=>"PC - (Pacote)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"44",
                "nome"=>"PÇ - (Peça)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"45",
                "nome"=>"RL - (Rolo)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"46",
                "nome"=>"GY - (Gray)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"47",
                "nome"=>"CGY - (Centgray)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"48",
                "nome"=>"PAR - (Par)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"49",
                "nome"=>"ADES - (Adesivo Transdérmico)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"50",
                "nome"=>"COM EFEV - (Comprimido Efervecente)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"51",
                "nome"=>"COM MST - (Comprimido Mastigável)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"52",
                "nome"=>"SACHE - (Sache)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"53",
                "nome"=>"M - (Metro)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"54",
                "nome"=>"M² - (Metro quadrado)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"55",
                "nome"=>"M³ - (Metro cúbico)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"56",
                "nome"=>"MG/peso - (Miligramas por peso)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"57",
                "nome"=>"MG/M² - (Miligramas por metro quadrado)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"58",
                "nome"=>"CAL - (Caloria)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"59",
                "nome"=>"UI/M² - (UI/M²)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"60",
                "nome"=>"UI/ML - (UI/ML)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],
            [
                "value"=>"61",
                "nome"=>"CM³ - (CM³)",
                "config"=>"",
                "pai"=>"8",
                "ordem"=>"1",
                "obs"=>"",
            ],

        ];

        foreach ($arr as $key => $value) {
            $d = $value;
            $d['token']=uniqid();
            Tag::create($d);
        }
    }
}
